name: Run automated tests
on:
  pull_request:
    branches:
      - main
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the project's source code from the repository.
      - name: Checkout project sources
        uses: actions/checkout@v4
# Step 2: Set up the Gradle build tool on the runner.
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 3: Run tests using the Gradle Wrapper.
      - name: Run Test with Gradle Wrapper
        run: ./gradlew test
